# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/data/code/cache/BlinkTree

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/data/code/cache/BlinkTree

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/data/code/cache/BlinkTree/CMakeFiles /mnt/d/data/code/cache/BlinkTree/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/data/code/cache/BlinkTree/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Trie

# Build rule for target.
Trie: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Trie
.PHONY : Trie

# fast build rule for target.
Trie/fast:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/build
.PHONY : Trie/fast

#=============================================================================
# Target rules for targets named bftree

# Build rule for target.
bftree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bftree
.PHONY : bftree

# fast build rule for target.
bftree/fast:
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/build
.PHONY : bftree/fast

src/Tool/Arraylist.o: src/Tool/Arraylist.c.o

.PHONY : src/Tool/Arraylist.o

# target to build an object file
src/Tool/Arraylist.c.o:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/Tool/Arraylist.c.o
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/Tool/Arraylist.c.o
.PHONY : src/Tool/Arraylist.c.o

src/Tool/Arraylist.i: src/Tool/Arraylist.c.i

.PHONY : src/Tool/Arraylist.i

# target to preprocess a source file
src/Tool/Arraylist.c.i:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/Tool/Arraylist.c.i
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/Tool/Arraylist.c.i
.PHONY : src/Tool/Arraylist.c.i

src/Tool/Arraylist.s: src/Tool/Arraylist.c.s

.PHONY : src/Tool/Arraylist.s

# target to generate assembly for a file
src/Tool/Arraylist.c.s:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/Tool/Arraylist.c.s
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/Tool/Arraylist.c.s
.PHONY : src/Tool/Arraylist.c.s

src/Tool/Tools.o: src/Tool/Tools.c.o

.PHONY : src/Tool/Tools.o

# target to build an object file
src/Tool/Tools.c.o:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/Tool/Tools.c.o
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/Tool/Tools.c.o
.PHONY : src/Tool/Tools.c.o

src/Tool/Tools.i: src/Tool/Tools.c.i

.PHONY : src/Tool/Tools.i

# target to preprocess a source file
src/Tool/Tools.c.i:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/Tool/Tools.c.i
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/Tool/Tools.c.i
.PHONY : src/Tool/Tools.c.i

src/Tool/Tools.s: src/Tool/Tools.c.s

.PHONY : src/Tool/Tools.s

# target to generate assembly for a file
src/Tool/Tools.c.s:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/Tool/Tools.c.s
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/Tool/Tools.c.s
.PHONY : src/Tool/Tools.c.s

src/Tool/bloom.o: src/Tool/bloom.c.o

.PHONY : src/Tool/bloom.o

# target to build an object file
src/Tool/bloom.c.o:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/Tool/bloom.c.o
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/Tool/bloom.c.o
.PHONY : src/Tool/bloom.c.o

src/Tool/bloom.i: src/Tool/bloom.c.i

.PHONY : src/Tool/bloom.i

# target to preprocess a source file
src/Tool/bloom.c.i:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/Tool/bloom.c.i
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/Tool/bloom.c.i
.PHONY : src/Tool/bloom.c.i

src/Tool/bloom.s: src/Tool/bloom.c.s

.PHONY : src/Tool/bloom.s

# target to generate assembly for a file
src/Tool/bloom.c.s:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/Tool/bloom.c.s
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/Tool/bloom.c.s
.PHONY : src/Tool/bloom.c.s

src/trie_tree/bftree.o: src/trie_tree/bftree.cpp.o

.PHONY : src/trie_tree/bftree.o

# target to build an object file
src/trie_tree/bftree.cpp.o:
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/trie_tree/bftree.cpp.o
.PHONY : src/trie_tree/bftree.cpp.o

src/trie_tree/bftree.i: src/trie_tree/bftree.cpp.i

.PHONY : src/trie_tree/bftree.i

# target to preprocess a source file
src/trie_tree/bftree.cpp.i:
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/trie_tree/bftree.cpp.i
.PHONY : src/trie_tree/bftree.cpp.i

src/trie_tree/bftree.s: src/trie_tree/bftree.cpp.s

.PHONY : src/trie_tree/bftree.s

# target to generate assembly for a file
src/trie_tree/bftree.cpp.s:
	$(MAKE) -f CMakeFiles/bftree.dir/build.make CMakeFiles/bftree.dir/src/trie_tree/bftree.cpp.s
.PHONY : src/trie_tree/bftree.cpp.s

src/trie_tree/test_trie_tree.o: src/trie_tree/test_trie_tree.cpp.o

.PHONY : src/trie_tree/test_trie_tree.o

# target to build an object file
src/trie_tree/test_trie_tree.cpp.o:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/trie_tree/test_trie_tree.cpp.o
.PHONY : src/trie_tree/test_trie_tree.cpp.o

src/trie_tree/test_trie_tree.i: src/trie_tree/test_trie_tree.cpp.i

.PHONY : src/trie_tree/test_trie_tree.i

# target to preprocess a source file
src/trie_tree/test_trie_tree.cpp.i:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/trie_tree/test_trie_tree.cpp.i
.PHONY : src/trie_tree/test_trie_tree.cpp.i

src/trie_tree/test_trie_tree.s: src/trie_tree/test_trie_tree.cpp.s

.PHONY : src/trie_tree/test_trie_tree.s

# target to generate assembly for a file
src/trie_tree/test_trie_tree.cpp.s:
	$(MAKE) -f CMakeFiles/Trie.dir/build.make CMakeFiles/Trie.dir/src/trie_tree/test_trie_tree.cpp.s
.PHONY : src/trie_tree/test_trie_tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Trie"
	@echo "... bftree"
	@echo "... src/Tool/Arraylist.o"
	@echo "... src/Tool/Arraylist.i"
	@echo "... src/Tool/Arraylist.s"
	@echo "... src/Tool/Tools.o"
	@echo "... src/Tool/Tools.i"
	@echo "... src/Tool/Tools.s"
	@echo "... src/Tool/bloom.o"
	@echo "... src/Tool/bloom.i"
	@echo "... src/Tool/bloom.s"
	@echo "... src/trie_tree/bftree.o"
	@echo "... src/trie_tree/bftree.i"
	@echo "... src/trie_tree/bftree.s"
	@echo "... src/trie_tree/test_trie_tree.o"
	@echo "... src/trie_tree/test_trie_tree.i"
	@echo "... src/trie_tree/test_trie_tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

